{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ojs-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ojs-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    {{- include "ojs-operator.selectorLabels" . | nindent 4 }}
{{- end }}
