apiVersion: v1
kind: ServiceAccount
metadata:
  name: ojs-operator-controller-manager
  namespace: ojs-system
  labels:
    app.kubernetes.io/name: ojs-k8s-operator
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/part-of: ojs
