//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another OJSCluster.
func (in *OJSCluster) DeepCopyInto(out *OJSCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the OJSCluster.
func (in *OJSCluster) DeepCopy() *OJSCluster {
	if in == nil {
		return nil
	}
	out := new(OJSCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSClusterList.
func (in *OJSClusterList) DeepCopyInto(out *OJSClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OJSCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSClusterList.
func (in *OJSClusterList) DeepCopy() *OJSClusterList {
	if in == nil {
		return nil
	}
	out := new(OJSClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSClusterSpec.
func (in *OJSClusterSpec) DeepCopyInto(out *OJSClusterSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.AutoScaling != nil {
		in, out := &in.AutoScaling, &out.AutoScaling
		*out = new(AutoScalingSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the OJSClusterSpec.
func (in *OJSClusterSpec) DeepCopy() *OJSClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OJSClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSClusterStatus.
func (in *OJSClusterStatus) DeepCopyInto(out *OJSClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSClusterStatus.
func (in *OJSClusterStatus) DeepCopy() *OJSClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OJSClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another BackendSpec.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another SecretKeyRef.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy returns a deep copy of the SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another AutoScalingSpec.
func (in *AutoScalingSpec) DeepCopyInto(out *AutoScalingSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the AutoScalingSpec.
func (in *AutoScalingSpec) DeepCopy() *AutoScalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another MonitoringSpec.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}
