//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another OJSCluster.
func (in *OJSCluster) DeepCopyInto(out *OJSCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the OJSCluster.
func (in *OJSCluster) DeepCopy() *OJSCluster {
	if in == nil {
		return nil
	}
	out := new(OJSCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSClusterList.
func (in *OJSClusterList) DeepCopyInto(out *OJSClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OJSCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSClusterList.
func (in *OJSClusterList) DeepCopy() *OJSClusterList {
	if in == nil {
		return nil
	}
	out := new(OJSClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSClusterSpec.
func (in *OJSClusterSpec) DeepCopyInto(out *OJSClusterSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.AutoScaling != nil {
		in, out := &in.AutoScaling, &out.AutoScaling
		*out = new(AutoScalingSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the OJSClusterSpec.
func (in *OJSClusterSpec) DeepCopy() *OJSClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OJSClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSClusterStatus.
func (in *OJSClusterStatus) DeepCopyInto(out *OJSClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSClusterStatus.
func (in *OJSClusterStatus) DeepCopy() *OJSClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OJSClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another BackendSpec.
func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the BackendSpec.
func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another SecretKeyRef.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy returns a deep copy of the SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another AutoScalingSpec.
func (in *AutoScalingSpec) DeepCopyInto(out *AutoScalingSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the AutoScalingSpec.
func (in *AutoScalingSpec) DeepCopy() *AutoScalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another MonitoringSpec.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSWorker.
func (in *OJSWorker) DeepCopyInto(out *OJSWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the OJSWorker.
func (in *OJSWorker) DeepCopy() *OJSWorker {
	if in == nil {
		return nil
	}
	out := new(OJSWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSWorkerList.
func (in *OJSWorkerList) DeepCopyInto(out *OJSWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OJSWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSWorkerList.
func (in *OJSWorkerList) DeepCopy() *OJSWorkerList {
	if in == nil {
		return nil
	}
	out := new(OJSWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSWorkerSpec.
func (in *OJSWorkerSpec) DeepCopyInto(out *OJSWorkerSpec) {
	*out = *in
	if in.JobTypes != nil {
		in, out := &in.JobTypes, &out.JobTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Queues != nil {
		in, out := &in.Queues, &out.Queues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.AutoScaling != nil {
		in, out := &in.AutoScaling, &out.AutoScaling
		*out = new(WorkerAutoScalingSpec)
		**out = **in
	}
	if in.GracefulShutdown != nil {
		in, out := &in.GracefulShutdown, &out.GracefulShutdown
		*out = new(GracefulShutdownSpec)
		**out = **in
	}
}

// DeepCopy returns a deep copy of the OJSWorkerSpec.
func (in *OJSWorkerSpec) DeepCopy() *OJSWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(OJSWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSWorkerStatus.
func (in *OJSWorkerStatus) DeepCopyInto(out *OJSWorkerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSWorkerStatus.
func (in *OJSWorkerStatus) DeepCopy() *OJSWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(OJSWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another WorkerAutoScalingSpec.
func (in *WorkerAutoScalingSpec) DeepCopyInto(out *WorkerAutoScalingSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the WorkerAutoScalingSpec.
func (in *WorkerAutoScalingSpec) DeepCopy() *WorkerAutoScalingSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerAutoScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another GracefulShutdownSpec.
func (in *GracefulShutdownSpec) DeepCopyInto(out *GracefulShutdownSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the GracefulShutdownSpec.
func (in *GracefulShutdownSpec) DeepCopy() *GracefulShutdownSpec {
	if in == nil {
		return nil
	}
	out := new(GracefulShutdownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another HardwareRequirement.
func (in *HardwareRequirement) DeepCopyInto(out *HardwareRequirement) {
	*out = *in
}

// DeepCopy returns a deep copy of the HardwareRequirement.
func (in *HardwareRequirement) DeepCopy() *HardwareRequirement {
	if in == nil {
		return nil
	}
	out := new(HardwareRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another ModelPolicy.
func (in *ModelPolicy) DeepCopyInto(out *ModelPolicy) {
	*out = *in
	if in.AllowedModels != nil {
		in, out := &in.AllowedModels, &out.AllowedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of the ModelPolicy.
func (in *ModelPolicy) DeepCopy() *ModelPolicy {
	if in == nil {
		return nil
	}
	out := new(ModelPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSAttestationPolicySpec.
func (in *OJSAttestationPolicySpec) DeepCopyInto(out *OJSAttestationPolicySpec) {
	*out = *in
	if in.JobTypes != nil {
		in, out := &in.JobTypes, &out.JobTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = make([]HardwareRequirement, len(*in))
		copy(*out, *in)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ModelPolicy != nil {
		in, out := &in.ModelPolicy, &out.ModelPolicy
		*out = new(ModelPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of the OJSAttestationPolicySpec.
func (in *OJSAttestationPolicySpec) DeepCopy() *OJSAttestationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(OJSAttestationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSAttestationPolicyStatus.
func (in *OJSAttestationPolicyStatus) DeepCopyInto(out *OJSAttestationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSAttestationPolicyStatus.
func (in *OJSAttestationPolicyStatus) DeepCopy() *OJSAttestationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(OJSAttestationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another OJSAttestationPolicy.
func (in *OJSAttestationPolicy) DeepCopyInto(out *OJSAttestationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the OJSAttestationPolicy.
func (in *OJSAttestationPolicy) DeepCopy() *OJSAttestationPolicy {
	if in == nil {
		return nil
	}
	out := new(OJSAttestationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSAttestationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another OJSAttestationPolicyList.
func (in *OJSAttestationPolicyList) DeepCopyInto(out *OJSAttestationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OJSAttestationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the OJSAttestationPolicyList.
func (in *OJSAttestationPolicyList) DeepCopy() *OJSAttestationPolicyList {
	if in == nil {
		return nil
	}
	out := new(OJSAttestationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *OJSAttestationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
